models:
  boltz2:
    app_name: "omtx-hub-boltz2-persistent"
    function_name: "boltz2_predict_modal"
    timeout: 3600
    gpu: "A100-40GB"
    description: "Boltz-2 biomolecular interaction prediction"
    parameters:
      - protein_sequences
      - ligands
      - use_msa_server
      - use_potentials
    
  rfantibody:
    app_name: "rfantibody-real-phase2"
    function_name: "rfantibody_predict_real_phase2"
    timeout: 3600
    gpu: "A100-40GB"
    description: "RFAntibody nanobody design pipeline"
    parameters:
      - target_pdb_content
      - target_chain
      - hotspot_residues
      - num_designs
      - framework
      - job_id
    
  chai1:
    app_name: "omtx-hub-chai1-persistent"
    function_name: "chai1_predict_modal"
    timeout: 2400
    gpu: "A100-40GB"
    description: "Chai-1 multi-modal molecular prediction"
    parameters:
      - protein_sequences
      - ligands
      - use_msa_server
      - num_steps

execution:
  max_retries: 3
  retry_delay: 5
  subprocess_timeout: 300
  auth_cache_ttl: 3600

logging:
  level: "INFO"
  include_modal_logs: true
  log_subprocess_output: true