# Cloud Build configuration for automated deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/om-models/omtx-hub-backend:latest', '-f', 'backend/Dockerfile.cloud_run_native', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/om-models/omtx-hub-backend:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'omtx-hub-backend'
      - '--image'
      - 'gcr.io/om-models/omtx-hub-backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '100'
      - '--max-instances'
      - '10'
      - '--service-account'
      - 'omtx-hub-service@om-models.iam.gserviceaccount.com'

# Store images in Container Registry
images:
  - 'gcr.io/om-models/omtx-hub-backend:latest'

# Set timeout for the build
timeout: '1200s'