apiVersion: v1
kind: ConfigMap
metadata:
  name: omtx-hub-config
  namespace: omtx-hub
data:
  GOOGLE_CLOUD_PROJECT: "om-models"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  RATE_LIMIT_ENABLED: "false"
  ENABLE_TRACING: "false"
  WORKERS: "1"