apiVersion: v1
kind: Secret
metadata:
  name: omtx-hub-secrets
  namespace: omtx-hub
type: Opaque
stringData:
  GCP_CREDENTIALS_JSON: |
    {
      "type": "service_account",
      "project_id": "om-models"
    }
  MODAL_TOKEN_ID: "placeholder"
  MODAL_TOKEN_SECRET: "placeholder"
  REDIS_PASSWORD: "placeholder"
  JWT_SECRET_KEY: "your-jwt-secret-key-here"
  MODAL_WEBHOOK_SECRET: "placeholder"