# Cloud Build configuration for OMTX-Hub Cloud Run Native
# Builds Docker image with GPU support and Boltz-2 integration

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-f', 'backend/Dockerfile.cloud_run_native',
      '-t', '${_IMAGE_NAME}',
      '.'
    ]
    dir: '/workspace'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']

# Substitutions for the build
substitutions:
  _IMAGE_NAME: 'gcr.io/om-models/omtx-hub-native:latest'

# Options for the build
options:
  # Use high-performance machine for faster builds
  machineType: 'E2_HIGHCPU_8'
  
  # Disk size for build
  diskSizeGb: 50

# Set timeout for build (important for GPU image builds)
timeout: '1200s'  # 20 minutes

# Images to be pushed to registry
images:
  - '${_IMAGE_NAME}'

# Tags for this build
tags:
  - 'omtx-hub'
  - 'cloud-run-native'
  - 'gpu-optimized'
