apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: omtx-hub-ingress
  namespace: omtx-hub
  annotations:
    # Use nginx ingress controller
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    
    # Performance annotations
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    
    # Rate limiting
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    
    # CORS handling for development
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    
    # SSL configuration (ready for cert-manager)
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    
spec:
  rules:
  # Default rule for IP access (current setup)
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: omtx-hub-backend-service
            port:
              number: 80
  # Future domain-based rule (uncomment when domain is configured)
  # - host: api.omtx-hub.com
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: omtx-hub-backend-service
  #           port:
  #             number: 80
  
  # TLS configuration (uncomment when domain and SSL are configured)
  # tls:
  # - hosts:
  #   - api.omtx-hub.com
  #   secretName: omtx-hub-tls

---
# Certificate Issuer for Let's Encrypt (requires cert-manager)
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-prod
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: admin@omtx-hub.com
#     privateKeySecretRef:
#       name: letsencrypt-prod
#     solvers:
#     - http01:
#         ingress:
#           class: nginx