FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
ARG DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && apt-get install -y software-properties-common
RUN DEBIAN_FRONTEND=noninteractive add-apt-repository -y ppa:deadsnakes/ppa
RUN apt-get install --no-install-recommends -y python3.10 python3-pip python3.10-venv pipx vim make wget git curl

# Set up Python
RUN python3.10 -m venv /opt/venv
ENV PATH='/opt/venv/bin:$PATH'
RUN pip install --upgrade pip

# Install Poetry
RUN pip install poetry

# Set working directory
WORKDIR /home

# Clone RFAntibody repository
RUN git clone https://github.com/RosettaCommons/RFantibody.git /home/rfantibody
WORKDIR /home/rfantibody

# Install RFAntibody dependencies
RUN poetry config virtualenvs.create false
RUN poetry install --no-dev

# Set environment variables
ENV PYTHONPATH=/home/rfantibody/src:$PYTHONPATH
ENV PATH=/home/rfantibody/bin:$PATH